#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# ACQUIA
%w{
  apache2
  apt
  build-essential
  git
  memcached
  php
  postfix
  vim
}.each do |cb|
  cookbook cb
end

cookbook "xdebug",
  :git => 'https://github.com/myplanetdigital/chef-xdebug.git',
  :ref => 'GH-xforty-1'

cookbook "phpcs",
  :git => 'https://github.com/myplanetdigital/chef-phpcs.git',
  :ref => 'v1.0.0'

cookbook "phpunit",
  :git => 'https://github.com/myplanetdigital/chef-phpunit.git',
  :ref => 'metadata-dep-fix'

cookbook 'drush',
  :git => 'https://github.com/patcon/chef-drush.git',
  :ref => 'msonnabaum-GH-10'

cookbook 'xhprof',
  :git => 'git://github.com/myplanetdigital/chef-xhprof.git',
  :ref => 'GH-msonnabaum-2'

cookbook 'percona',
  :git => 'https://github.com/msonnabaum/chef-percona.git',
  :ref => 'master'

cookbook 'varnish',
  :git => 'https://github.com/opscode-cookbooks/varnish.git',
  :ref => '0.9.2'
