#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

cookbook "apache2"
cookbook "apt"
cookbook "bash",
  :git => "https://github.com/myplanetdigital/chef-bash.git",
  :ref => "feature/bash_profile-resource"
cookbook "build-essential"
cookbook "drush",
  :git => "https://github.com/msonnabaum/chef-drush.git",
  :ref => "master"
cookbook "git"
cookbook "memcached"
cookbook "mysql",
  :git => "https://github.com/myplanetdigital/chef-mysql.git",
  :ref => "COOK-1610-bypass-preseed"
cookbook "percona",
  :git => "https://github.com/myplanetdigital/chef-percona.git",
  :ref => "master"
cookbook "php"
cookbook "phpcs",
  :git => "https://github.com/myplanetdigital/chef-phpcs.git",
  :ref => "master"
cookbook "phpunit",
  :git => "https://github.com/myplanetdigital/chef-phpunit.git",
  :ref => "GH-9-pear-errors"
cookbook "postfix"
cookbook "varnish"
cookbook "vim"
cookbook "xdebug",
  :git => "https://github.com/myplanetdigital/chef-xdebug.git",
  :ref => "GH-5-php_pear-zend-template"
cookbook "xhprof",
  :git => "https://github.com/myplanetdigital/chef-xhprof.git",
  :ref => "GH-msonnabaum-3"
