#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# ACQUIA
%w{
  apache2
  apt
  build-essential
  git
  memcached
  php
  postfix
  varnish
  vim
}.each do |cb|
  cookbook cb
end

cookbook "xdebug",
  :git => 'https://github.com/myplanetdigital/chef-xdebug.git',
  :ref => 'GH-xforty-1'

cookbook 'drush',
  :git => 'https://github.com/msonnabaum/chef-drush.git',
  :ref => 'v0.10.0'

cookbook 'xhprof',
  :git => 'git://github.com/myplanetdigital/chef-xhprof.git',
  :ref => 'GH-msonnabaum-2'

cookbook 'percona',
  :git => 'https://github.com/msonnabaum/chef-percona.git',
  :ref => 'master'
